"""empty message

Revision ID: 204306fb46cb
Revises: 
Create Date: 2017-11-27 22:24:30.330323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '204306fb46cb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_column('things', 'link')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('things', sa.Column('link', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
