"""empty message

Revision ID: 791cb4cc9b3a
Revises: 67c0f97c97a8
Create Date: 2017-11-29 19:47:24.928302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '791cb4cc9b3a'
down_revision = '67c0f97c97a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('things', 'date',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('things', 'date',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###
